\@setckpt{introduction/introduction}{
\@setckpt{simplechecks/simplechecks}{
\@writefile{lof}{\contentsline {figure}{\numberline {1}{\ignorespaces three example of simulated trace with on top of each figure the signal in ADC counts, and on the bottom the signal in sigma}}{3}{figure.1}}
\@writefile{lof}{\select@language{english}}
\@writefile{lot}{\select@language{english}}
\@writefile{toc}{\contentsline {chapter}{Bibliography}{4}{figure.1}}
\@writefile{toc}{\contentsline {section}{\numberline {1}Introduction}{2}{section.1}}
\@writefile{toc}{\contentsline {section}{\numberline {2}Checks}{3}{section.2}}
\@writefile{toc}{\contentsline {subsection}{\numberline {2.1}Gorham shower}{3}{subsection.2.1}}
\@writefile{toc}{\select@language{english}}
\AC@reset@newl@bel
\AtEndDocument{\ifx\hyper@anchor\@undefined
\HyperFirstAtBeginDocument{\ifx\hyper@anchor\@undefined
\bibdata{thebib}
\bibstyle{atlasnote}
\citation{gorham}
\citation{imen2016}
\fi}
\fi}
\gdef\HyperFirstAtBeginDocument#1{#1}
\gdef\contentsline#1#2#3#4{\oldcontentsline{#1}{#2}{#3}}
\gdef\newlabel#1#2{\newlabelxx{#1}#2}
\gdef\newlabelxx#1#2#3#4#5#6{\oldnewlabel{#1}{{#2}{#3}}}
\global\let\hyper@last\relax 
\global\let\oldcontentsline\contentsline
\global\let\oldnewlabel\newlabel
\let\contentsline\oldcontentsline
\let\newlabel\oldnewlabel
\newlabel{fig:traceex}
\providecommand\HyField@AuxAddToCoFields[2]{}
\providecommand\HyField@AuxAddToFields[1]{}
\providecommand\HyperFirstAtBeginDocument{\AtBeginDocument}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\select@language{english}
\setcounter{@todonotes@numberoftodonotes}{0}
\setcounter{@todonotes@numberoftodonotes}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{LN@truepage}{2}
\setcounter{LN@truepage}{3}
\setcounter{bookmark@seq@number}{1}
\setcounter{bookmark@seq@number}{3}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{figure}{0}
\setcounter{figure}{1}
\setcounter{float@type}{4}
\setcounter{float@type}{4}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{linenumber}{11}
\setcounter{linenumber}{18}
\setcounter{lofdepth}{1}
\setcounter{lofdepth}{1}
\setcounter{lotdepth}{1}
\setcounter{lotdepth}{1}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{page}{3}
\setcounter{page}{4}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{section@level}{1}
\setcounter{section@level}{2}
\setcounter{section}{1}
\setcounter{section}{2}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{1}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{table}{0}
\setcounter{table}{0}
}
}
