\newlabel{fig:distamp}
\newlabel{fig:filter}
\newlabel{fig:hexagon}
\newlabel{fig:linenoline}
\newlabel{fig:longwf}
\newlabel{fig:monit}
\newlabel{fig:monit}
\newlabel{fig:monit}
\newlabel{fig:newnono}
\newlabel{fig:noisefloor}
\newlabel{fig:pics}
\newlabel{fig:specpeak}
\newlabel{fig:transient}
\newlabel{fig:wf}
\newlabel{sec:update}
\newlabel{tab:baselines}
\newlabel{tab:boxnumber}
